source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ZXKit_Example', :exclusive => true do
  pod "ZXKit", :path => "../"
end

target 'ZXKit_Tests', :exclusive => true do
  pod "ZXKit", :path => "../"

  
end
